### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Troughy** [Zile995/Ryzen-2600_RX-580-GPU-Passthrough#1]
Just wanted to thank you for this. Thanks to your guide, I was able to get GPU passthrough working with my RX 570 (and Ryzen 5 2600)
A few things I did differently:
- kernel parameters - instead of `iommu=pt iommu=1` I did `amd_iommu=on iommu=pt`. This was from another guide, never even tested the first one, seems weird to be setting the same thing twice.
- ~I had a black screen with the vbios that amdvbflash dumped, I also tried with echo/cat (/sys/bus/pci/devices/.../rom), same issue. Then I downloaded the latest vbios for my graphics card from techpowerup.com and it worked.~ With the techpowerup.com vbios, the VM booted but I always had a black screen while it was booting, and also sometimes it didn't boot at all, I just got a black screen. I dumped the vbios again today (April 3) with amdvbflash and this time it worked, and I can also see the VM booting (UEFI logo, Windows 11 boot animation). I'll edit this if I get any black screens.
Also I couldn't install Radeon Software with the minimal setup (I got the 'This installer is intended to be deployed only on an AMD system' error), I had to get the .exe for the RX 570 and that worked
- I couldn't really get audio to work, so I ended up passing through the audio controller - and for that to work (because my IOMMU groups were messed up) I had to install a patched kernel (linux-vfio on aur). But I'm glad I did because it makes things so much simpler, after I turned on ACS in the UEFI (and set a few extra kernel parameters), all I need to do is add the ID (from lspci -nnk) of the device to the vfio-pci.ids kernel parameter and it seperates it into its own iommu group

**Comment by Zile995** [comment]
@Troughy  I'm glad it works.

Regarding the things mentioned:

- `iommu=1` is a generic setting and `amd_iommu=on` is vendor specific setting. So, both should work fine.  https://www.mail-archive.com/libvirt-users@redhat.com/msg12136.html
- Well, amdvbflash works for me. I might add info on downloading the bios from the techpowerup.com site.
- Cool. I think ACS override support is also included with Zen Kernel.

**Comment by Troughy** [comment]
> @Troughy I'm glad it works.
> 
> Regarding the things mentioned:
> 
>     * `iommu=1` is a generic setting and `amd_iommu=on` is vendor specific setting. So, both should work fine.  https://www.mail-archive.com/libvirt-users@redhat.com/msg12136.html
> 
>     * Well, amdvbflash works for me. I might add info on downloading the bios from the techpowerup.com site.
> 
>     * Cool. I think ACS override support is also included with Zen Kernel.

You're right, the Arch wiki says (regarding IOMMU kernel parameters): `For AMD CPUs (AMD-Vi), it is on if kernel detects IOMMU hardware support from BIOS.`
I read about possible security issues with ACS override and ended up going back to default kernel and using only the ACS option in the UEFI, the IOMMU groups are the same (which means I didn't even set up the linux-vfio kernel properly?). But thankfully everything works, I managed to pass through the audio controller and a USB controller for 2 USB3.1 ports. Thanks again.

**Comment by Troughy** [comment]
~Turns out I don't even need the vbios file. The VM works fine without it.~
The VM does work without a vbios file, or with the techpowerup.com one, but sometimes it doesn't boot (black screen, no Windows 11 startup sound)
Turns out, amdvbflash works just fine (maybe it doesn't always work?), and now I don't get a black screen **while** the VM is booting. I hope I won't be getting black screens anymore.
